name: tekartik_firebase_firestore_sim_io
description: Firebase firestore simulation
version: 0.3.6
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_firebase_sim_io:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim_io
      ref: dart2
    version: 0.3.6
  tekartik_firebase_firestore_sim:
    git:
      url: git://github.com/tekartik/firestore.dart
      path: firestore_sim
      ref: dart2
    version: 0.3.6
  tekartik_firebase_firestore_sembast:
    git:
      url: git://github.com/tekartik/firestore.dart
      path: firestore_sembast
      ref: dart2
    version: 0.3.6

dev_dependencies:
  test: "^1.0.0"
  dev_test: '>=0.12.0-dev.1'
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"

dependency_overrides:
  tekartik_firebase_firestore_test:
    path: ../firestore_test
  tekartik_firebase_firestore_sim:
    path: ../firestore_sim
  tekartik_firebase_firestore:
    path: ../firestore
  tekartik_firebase_firestore_sembast:
    path: ../firestore_sembast

