name: tekartik_firebase_firestore_node
description: Firebase firestore server node
version: 0.4.1+1
publish_to: none

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  uuid: '>=1.0.0'
  tekartik_firebase_firestore:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2
    version: '>=0.5.0'
  tekartik_firebase_node:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_node
      ref: dart2
    version: '>=0.3.7'
  firebase_functions_interop: ">=1.0.2"
  firebase_admin_interop: ">=1.2.2"

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
  build_runner: ">=0.9.1"
  build_node_compilers: ">=0.1.8"
  build_test: ">=0.10.3"
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_firestore_test:
    path: ../firestore_test
  tekartik_firebase_firestore:
    path: ../firestore
  quiver_hashcode: '>=1.0.0'
#  firebase_admin_interop:
#    path: ../../firebase-admin-interop