# Created with https://github.com/dart-lang/mono_repo
language: dart
dart:
  - stable
  - 2.6.1
  - dev
sudo: required
addons:
  chrome: stable

script:
  - dart tool/travis.dart

cache:
  directories:
    - $HOME/.pub-cache