name: tekartik_firebase_firestore_sembast
description: Firebase firestore sembast
version: 0.4.4
publish_to: none

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  sembast: '>=1.15.2-dev'
  uuid: '>=1.0.0'
  tekartik_firebase_firestore:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2
    version: '>=0.4.2'
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
    version: '>=0.3.7'

dev_dependencies:
  test: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  tekartik_firebase_firestore_test:
    path: ../firestore_test

dependency_overrides:
  tekartik_firebase_firestore:
    path: ../firestore
