name: tekartik_firebase_firestore
description: Firebase firestore core
version: 0.3.5
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.3.5'
dev_dependencies:
  test: "^1.0.0"
